# Generated by Django 4.2 on 2023-04-12 08:10

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "item_id",
                    models.IntegerField(
                        primary_key=True, serialize=False, verbose_name="ID товара"
                    ),
                ),
                ("category", models.CharField(max_length=50)),
                ("subcategory", models.CharField(max_length=50)),
                ("photo_id", models.CharField(max_length=100)),
                ("description", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "Товар",
                "verbose_name_plural": "Товары",
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "order_id",
                    models.IntegerField(
                        primary_key=True, serialize=False, verbose_name="Номер заказа"
                    ),
                ),
                (
                    "user_id",
                    models.BigIntegerField(verbose_name="Телеграмм ID пользователя"),
                ),
                ("item_id", models.IntegerField(verbose_name="ID товара")),
                ("count", models.IntegerField(verbose_name="Количество")),
            ],
            options={
                "verbose_name": "Заказ",
                "verbose_name_plural": "Все заказы",
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "user_id",
                    models.BigIntegerField(
                        primary_key=True,
                        serialize=False,
                        verbose_name="Телеграмм ID пользователя",
                    ),
                ),
            ],
            options={
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользователи",
            },
        ),
    ]
